name: CI

on:
  push:
    # Run on the main branch
    branches:
      - main
      - release/*
  # Also on PRs, just be careful not to publish anything
  pull_request:
  # Allow to be called from other workflows (like "release")
  workflow_call:
  # But don't trigger on tags, as they are covered by the "release.yaml" workflow

jobs:

  common:
    uses: scm-rs/shared-workflows/.github/workflows/ci.yaml@main
    with:
      matrix_include: |
        [
          {
            "os": "ubuntu-22.04",
            "install": "sudo apt install clang llvm pkg-config nettle-dev"
          },
          {
            "os": "windows-2022",
            "args": "--features crypto-cng --no-default-features",
          },
          {
            "os": "macos-14",
          }
        ]

  ci:
    runs-on: ubuntu-latest
    needs:
      - common
    if: always()
    steps:
      - name: Success
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Failure
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
